### PR TITLE
Add Pocket support

### PR DESCRIPTION
**Pull request by lnalex**
Using _Rainbowstream_ at work, I needed to save links for later. So I implemented [Pocket](https://getpocket.com) support to connect to your Pocket account and once at home looking at your saved links.

It's disabled by default, I don't want to force the users to use it.

**For developers:**
You need to create an app [here](http://getpocket.com/developer/apps/) (Platform: Web) and add to your `customer.py` :

     PCKT_CONSUMER_KEY = 'xxxx-xxxxxxxxxxxxxxxxxxxxxxxx' # Your Pocket application's API key

### CODE REVIEW

**Comment by DTVD** [comment]
Seems interesting ! Will take a look and test for a while. Thanks!

**Comment by lnalex** [comment]
Any feedback ?

**Comment by lnalex** [comment]
One year later... What's up ?

**Comment by DTVD** [comment]
Very sorry, I was offline for quite a long time. Checking this and will include in next release if possible

**Comment by DTVD** [comment]
Thanks for your awesome work!

**Pull request merged**
